package be.cetic.simqri.design.templates;

import be.cetic.simqri.metamodel.Model;


/**
 * @author FK
 * @version 1.0
 * 
 * Check the validity of queries written by the user 
 */
public class CheckQueries { 
	
	/**
	 * 
	 * @param model The instance of the graphical model generated by the user
	 * @return true if all queries are ok, false otherwise
	 * 
	 * This method calls a scala method from a scala plug-in which parse probes to the OscaR DES Engine and check the validity of all of them
	 */
	public boolean checkValidity(Model model) {
		//SimQRiSirius sim = new SimQRiSirius();
		//System.err.println("tesJ");
		return true;
	}
	
	public static void main(String[] args) {

	}
	

}
