package be.cetic.simqri.design.templates;

import be.cetic.simqri.cockpit.main.CheckQueries;
import be.cetic.simqri.metamodel.Model;

/**
 * 
 * @author Francois Kouptchinsky
 * @since 06/07/2016
 * @version 1.0
 * 
 * Contains checks about queries written by the user in the Queries Table
 */
public class CheckQuery {
	
	public static String errMessages;
	
	/** 
	 * 
	 * @param model the instance of EMF metamodel
	 * @return the queries error message generated by OscaR-DES
	 */
	public String thisQueryIsValid(Model model) {
		errMessages = CheckQueries.dynamicCheck(model);
		return errMessages;
	}
}
