package be.cetic.simqri.design.templates;

import java.util.ArrayList;

import be.cetic.simqri.cockpit.main.CheckQueries;

import be.cetic.simqri.metamodel.Model;

/**
 * 
 * @author Francois Kouptchinsky
 * @since 06/07/2016
 * @version 1.0
 * 
 * Java extension that executes a dynamic check for all queries written by the user in the Queries Table
 */
public class CheckQuery {
	
	public static ArrayList<String> errMessages;
	
	/** 
	 * 
	 * @param model the instance of EMF metamodel
	 * @return the queries error message generated by OscaR-DES
	 */
	public String thisQueryIsValid(Model model) {
		errMessages = CheckQueries.dynamicCheck(model);
		String str = "";
		for(String error : errMessages) {
			str += error+"\n";
		}
		return str;
	}
}
