<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="metamodel" nsURI="http://www.example.org/metamodel" nsPrefix="metamodel">
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="query" upperBound="-1"
        eType="#//Query" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="orderOnStockThreshold"
        upperBound="-1" eType="#//OrderOnStockThreshold" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" upperBound="-1"
        eType="#//Component" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="flow" upperBound="-1" eType="#//Flow"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Query">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="query"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Storage" eSuperTypes="#//Component">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="#//PositiveIntNotNull"
        defaultValueLiteral="100"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="initialContent" eType="#//PositiveInt"
        defaultValueLiteral="100"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="overflow" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="storageOutputFlow" upperBound="-1"
        eType="#//StorageOutputFlow" eOpposite="#//StorageOutputFlow/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="orderOnStockThreshold"
        upperBound="-1" eType="#//OrderOnStockThreshold" eOpposite="#//OrderOnStockThreshold/storage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="processOutputFlow" upperBound="-1"
        eType="#//ProcessOutputFlow" eOpposite="#//ProcessOutputFlow/destination"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Supplier" eSuperTypes="#//Component">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deliveredPercentage" eType="#//Percent"
        defaultValueLiteral="100"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refillPolicy" upperBound="-1"
        eType="#//OrderOnStockThreshold" eOpposite="#//OrderOnStockThreshold/supplier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supplierDelay" lowerBound="1"
        eType="#//Probability" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BatchProcess" eSuperTypes="#//Process">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="percentageOfSuccess" eType="#//Percent"
        defaultValueLiteral="100"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfLines" eType="#//PositiveIntNotNull"
        defaultValueLiteral="3"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputs" upperBound="-1"
        eType="#//Output" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OrderType">
    <eLiterals name="FIXED"/>
    <eLiterals name="REFILL" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OutputType">
    <eLiterals name="SUCCESS"/>
    <eLiterals name="FAILURE" value="1"/>
    <eLiterals name="LOWER_QUALITY" value="2"/>
    <eLiterals name="TRASH" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Output">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//OutputType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="processOutputFlow" upperBound="-1"
        eType="#//ProcessOutputFlow" eOpposite="#//ProcessOutputFlow/source"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StorageOutputFlow" eSuperTypes="#//Flow">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Storage" eOpposite="#//Storage/storageOutputFlow"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="destination" lowerBound="1"
        eType="#//Process" eOpposite="#//Process/storageOutputFlow"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessOutputFlow" eSuperTypes="#//Flow">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Output" eOpposite="#//Output/processOutputFlow"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="processOutputFlowDelay"
        lowerBound="1" eType="#//Probability" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="destination" lowerBound="1"
        eType="#//Storage" eOpposite="#//Storage/processOutputFlow"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Process" abstract="true" eSuperTypes="#//Component">
    <eStructuralFeatures xsi:type="ecore:EReference" name="storageOutputFlow" upperBound="-1"
        eType="#//StorageOutputFlow" eOpposite="#//StorageOutputFlow/destination"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="duration" lowerBound="1"
        eType="#//Probability" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OrderOnStockThreshold">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="period" eType="#//PositiveDouble"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="threshold" eType="#//PositiveInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="orderQuantity" eType="#//PositiveInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="orderType" eType="#//OrderType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supplier" lowerBound="1"
        eType="#//Supplier" eOpposite="#//Supplier/refillPolicy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="storage" lowerBound="1"
        eType="#//Storage" eOpposite="#//Storage/orderOnStockThreshold"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Component" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Flow" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="quantity" lowerBound="1"
        eType="#//Probability" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Probability" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Distribution" abstract="true" eSuperTypes="#//Probability"/>
  <eClassifiers xsi:type="ecore:EClass" name="Cauchy" eSuperTypes="#//Distribution">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scale" eType="#//PositiveDoubleNotNull"
        defaultValueLiteral="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Binomial" eSuperTypes="#//Distribution">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nbrOfTrial" eType="#//PositiveIntNotNull"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="probaOfSuccess" eType="#//ProbaDouble"
        defaultValueLiteral="0.0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Beta" eSuperTypes="#//Distribution">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="freedomDegreeA" eType="#//PositiveDoubleNotNull"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="freedomDegreeB" eType="#//PositiveDoubleNotNull"
        defaultValueLiteral="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Scalar" eSuperTypes="#//Probability">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//PositiveInt"
        defaultValueLiteral="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChiSquare" eSuperTypes="#//Distribution">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="degreeOfFreedom" eType="#//PositiveIntNotNull"
        defaultValueLiteral="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Percent" instanceClassName="java.lang.Double">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="baseType" value="http://www.eclipse.org/emf/2002/Ecore#EDouble"/>
      <details key="minInclusive" value="0"/>
      <details key="maxInclusive" value="100"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="PositiveInt" instanceClassName="java.lang.Integer">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="baseType" value="http://www.eclipse.org/emf/2002/Ecore#EInt"/>
      <details key="minInclusive" value="0"/>
      <details key="name" value="PositiveInt"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="PositiveDouble" instanceClassName="java.lang.Double">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="minInclusive" value="0"/>
      <details key="baseType" value="http://www.eclipse.org/emf/2002/Ecore#EDouble"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="PositiveIntNotNull" instanceClassName="java.lang.Integer">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="baseType" value="http://www.eclipse.org/emf/2002/Ecore#EInt"/>
      <details key="minInclusive" value="1"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiracDelta" eSuperTypes="#//Distribution">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mean" eType="#//PositiveIntNotNull"
        defaultValueLiteral="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Exponential" eSuperTypes="#//Distribution">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scale" eType="#//PositiveDoubleNotNull"
        defaultValueLiteral="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FDistribution" eSuperTypes="#//Distribution">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="freedomDegreeA" eType="#//PositiveDoubleNotNull"
        defaultValueLiteral="1">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="freedomDegreeA"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="freedomDegreeB" eType="#//PositiveDoubleNotNull"
        defaultValueLiteral="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Gamma" eSuperTypes="#//Distribution">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shape" eType="#//PositiveDoubleNotNull"
        defaultValueLiteral="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Geometric" eSuperTypes="#//Distribution">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="probaOfSuccess" eType="#//ProbaDoubleNotNull"
        defaultValueLiteral="0.1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LogNormal" eSuperTypes="#//Distribution">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scale" eType="#//PositiveDoubleNotNull"
        defaultValueLiteral="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="PositiveDoubleNotNull" instanceClassName="java.lang.Double">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="PositiveDoubleNotNull"/>
      <details key="minExclusive" value="0"/>
      <details key="baseType" value="http://www.eclipse.org/emf/2002/Ecore#EDouble"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Gaussian" eSuperTypes="#//Distribution">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scale" eType="#//PositiveDoubleNotNull"
        defaultValueLiteral="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pareto" eSuperTypes="#//Distribution">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shape" eType="#//PositiveDoubleNotNull"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scale" eType="#//PositiveDoubleNotNull"
        defaultValueLiteral="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Poisson" eSuperTypes="#//Distribution">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="interval" eType="#//PositiveDoubleNotNull"
        defaultValueLiteral="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StudentsT" eSuperTypes="#//Distribution">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="degreeOfFreedom" eType="#//PositiveDoubleNotNull"
        defaultValueLiteral="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Uniform" eSuperTypes="#//Distribution">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minimum" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximum" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0.0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Weibull" eSuperTypes="#//Distribution">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shape" eType="#//PositiveDouble"
        defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scale" eType="#//PositiveDouble"
        defaultValueLiteral="0.0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="ProbaDouble" instanceClassName="java.lang.Double">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="baseType" value="http://www.eclipse.org/emf/2002/Ecore#EDouble"/>
      <details key="minInclusive" value="0"/>
      <details key="maxInclusive" value="1"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="ProbaDoubleNotNull" instanceClassName="java.lang.Double">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="baseType" value="http://www.eclipse.org/emf/2002/Ecore#EDouble"/>
      <details key="maxInclusive" value="1"/>
      <details key="minExclusive" value="0"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConveyorBelt" eSuperTypes="#//Process">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minimalSeparationBetweenBatches"
        eType="#//PositiveDouble" defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="output" eType="#//Output"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
